-
  branches:
    only:
    - develop
  version: 1.0.{build}-dev
  configuration: Debug
  install:
    - nuget restore
  image: Visual Studio 2017
  build_script:
  - ps: dotnet publish -c Debug
  artifacts:
   - path: '\MrCMS.Web\bin\Debug\netcoreapp2.1\publish'
     name: MrCMS.Web
     type: WebDeployPackage
  test_script:
  - ps: Get-ChildItem . -File -recurse -Filter *.Tests.csproj | Foreach { dotnet test $_.fullname }
-
  branches:
    only:
    - master
  version: 1.0.{build}-master
  configuration: Release
  image: Visual Studio 2017
  install:
    - nuget restore
  build_script:
  - ps: dotnet publish -c Release
  artifacts:
   - path: '\MrCMS.Web\bin\Debug\netcoreapp2.1\publish'
     name: MrCMS.Web
     type: WebDeployPackage
