-
  branches:
    only:
    - develop
  version: 1.0.{build}-dev
  configuration: Debug
  install:
    - nuget restore
  image: Visual Studio 2017
  build:
    publish_aspnet_core: true
    parallel: true
    verbosity: minimal
  # after_build:
  # - ps: dotnet publish -c Debug
-
  branches:
    only:
    - master
  version: 1.0.{build}-master
  configuration: Release
  image: Visual Studio 2017
  install:
    - nuget restore
  build:
    publish_aspnet_core: true
    parallel: true
    verbosity: minimal
  # after_build:
  # - ps: dotnet publish -c Release
